### ISSUE TITLE
Notifications need multiple click to get to a post sometimes

### ISSUE THREAD

**Issue by RaulG27** [brockenbrough/ssu-social-frontend#130] opened 2024-11-26 07:12 UTC
How to find the bug:

- Go to the "Discover" page.
- Tap on your notifications and select a "like" from a person from a while ago
- Click on the like multiple times slowly
- Observe scrollwheel as posts start loading little by little

Note that the posts continue loading until the liked post is loaded in. After it is loaded in then you click on the notification one more time and it goes straight to your post

**Comment by brockenbrough** [comment] 2024-12-03 17:48
This is a duplicate of #108.

**Closed as completed** 2024-12-03 17:49 UTC
Labels: state-closed-duplicate
