### ISSUE TITLE
Hovering over your username on a post shows the incorrect edit profile button

### ISSUE THREAD

**Issue by Grummps** [brockenbrough/ssu-social-frontend#80] opened 2024-11-21 16:54 UTC
1. Create a post
2. Go to discover 
3. Hover over your username 
4. Notice the "edit profile" button, should either be "edit bio" or shouldn't be there

**Comment by karanssu** [comment] 2024-12-03 17:29
Duplicate of #111 and it's fixed

**Closed as not planned by karanssu** 2024-12-03 17:29 UTC
Labels: state-closed-duplicate, priority-low
